### ISSUE TITLE
Powah recipes not appearing in JEI

### ISSUE THREAD

**Issue by BigMentalProblems** [Technici4n/Powah#188] opened 2024-09-03 13:27 UTC
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.21.1
- NeoForge: 21.1.31
- Powah: 6.1.0

#### Issue description:
Idk if this is a powah issue or JEI issue but I'm writing this in here, so when i started my survival world and played for a while i wanted to start on powah but when i went to look at the recipes in jei they weren't there 

#### Steps to reproduce:
open minecraft neoforge mentioned at the top and make a new survival world and try to see the energizing recipes

#### Is this a crash?, please include it here: (Recommended to use [Gist](https://gist.github.com/))
no

**Comment by BigMentalProblems** [comment] 2024-09-03 13:30
My pc detected the file as a virus so no tnx

**Comment by Mithi83** [comment] 2024-09-04 19:16
Duplicate of #186

**Comment by Saereth** [comment] 2024-09-18 06:55
Not exactly, although that issue was closed as complete since mezz reintroduced JEI compat it was only for 1.21 build, https://github.com/Technici4n/Powah/commit/ac6a5b324c01959942d950a3e0a46f28e6bbbb7b
This released version doesnt actually work on 1.21.1 and if you try to launch 6.1.1 (tagged for mc 1.21.0) on mc 1.21.1 it will crash. 
6.1.0 for mc 1.21.1 is the only one that currently works on 1.21.1.

**Comment by Technici4n** [comment] 2024-09-18 23:03
Oops I merged it in the 1.21 branch instead of the 1.21.1 branch (I don't even know why both exist). Fixed now in 6.1.2!

**Closed as completed by Technici4n** 2024-09-18 23:03 UTC
