### ISSUE TITLE
Powah Crashes With Too Many Energy Cables [Issue Originally Marked As Solved, Definitely Not Solved]

### ISSUE THREAD

**Issue by SaltiestMeatBall** [Technici4n/Powah#133] opened 2024-01-21 00:04 UTC
#### Version: (make sure you are on the latest version before reporting): 

- Minecraft: 1.19.2
- Forge: 43.2.14
- Powah: 4.0.11

#### Issue description:

When hooking together 50 or more Energy Cables precisely, server immediately falls behind by thousands of ticks before crashing 3-5 minutes later. Issue stops when you use less cables. This issue was posted back in late 2022 and closed for some reason, issue still remains and not solved by any Powah patching. If any was done.

#### Steps to reproduce:

Connect 50 or more energy cables of any quality together and then power them. Then, watch the console as your server tick rate rapidly deteriotates.

#### Is this a crash?, please include it here: (Recommended to use [Gist](https://gist.github.com/))

This is a crash.

**Comment by Technici4n** [comment] 2024-01-21 08:15
Please provide a crash log and ideally a server profile (from Spark) as well.

**Comment by Entoarox** [comment] 2024-01-23 08:25
Have been experiencing this issue as well, the cause seems to be some kind of extreme memory leak, the thermo's especially suffered hard, with nearly 7GB of leaked memory occuring within just 30 mins.
But other tiles suffer the same issue, just not to the extreme extent that thermo's did.
Amongst these leaky tiles are the cables themselves, and as they get used a lot, they may not individually leak heavily, but their combined leakage is extreme.

If it is of any aid, I host a server that was on 1.20.1 previously (We downgraded due to how unstable 1.20 modpacks still tend to be) and did not suffer these memory issues there.
So either there is a change made to Powah in the 1.20 port that fixed the leak, or a change to Forge itself that did so.

I have multiple heap traces if you desire one, but these tend towards the 10+GB in size as a result of this memory leakage, so not sure how I would share any of them.

**Comment by Technici4n** [comment] 2024-01-23 08:44
I know of one such problem, but that was fixed in 1.19.2. A heap dump would be useful if you manage to upload it.

**Comment by Technici4n** [comment] 2024-01-23 08:45
(Or potentially you could open the heap dump and see what is happening)

**Comment by Entoarox** [comment] 2024-01-23 14:22
> (Or potentially you could open the heap dump and see what is happening)

I did open the heap dump, I used Eclipse Memory Analyser to process it, and it is what reported Powah's tiles as the issue, as even compressed the heap dump is still over 2GB I've been unable to get it uploaded, but here is a set of screenshots of the report made by EMA.
![image](https://github.com/Technici4n/Powah/assets/4977187/45ce0a9f-643f-4bce-a167-4d5a3064d0f8)
![image](https://github.com/Technici4n/Powah/assets/4977187/5e1cd354-bd08-41e3-a223-ae051d3f727c)
![image](https://github.com/Technici4n/Powah/assets/4977187/9462df60-b763-48fd-8650-60888c7d9ef9)

After I removed these two tiles from the world completely, The next dump reported the Solar panels and Energy Cells as most likely leak suspects.

Since removing all of these (Which accounted to about 200 blocks at most, most of them cables), memory usage has drastically decreased, and OutOfMemory no longer occurs. (Previously, it was guaranteed to occur after about 10 hours of up-time)


If there is any more detail or information I can provide, Please let me know, unfortunately transferring the heap file is just a nightmare due to even it's compressed size...

**Comment by Technici4n** [comment] 2024-01-23 14:43
Wow that's crazy! Can you maybe look into what makes these `ThermoTile`s and `CableTile`s so fat? (Which fields)

**Comment by Entoarox** [comment] 2024-01-23 15:15
> Wow that's crazy! Can you maybe look into what makes these `ThermoTile`s and `CableTile`s so fat? (Which fields)

If you can give me instructions on how, I would be more then happy to, I am not familiar with EMA, so I have no clue where to even start looking I am afraid.

**Comment by Entoarox** [comment] 2024-01-23 15:22
I believe I might have found what you wanted to know, though I am not certain as I stumbled across this bit just going around poking at things...
![image](https://github.com/Technici4n/Powah/assets/4977187/bde46e68-ea25-4be6-8336-4640423589f4)

**Comment by Technici4n** [comment] 2024-01-23 15:28
Ah yes exactly, this indicates that the `capabilities` object is what is using all the RAM. Can you look at what is inside of it (and so on... ;))

**Comment by Entoarox** [comment] 2024-01-23 15:32
I have, and from what I can tell (As a complete java novice), this is prolly where the issue sits, given that it kinda seems like one massively oversized HashMap to have...
![image](https://github.com/Technici4n/Powah/assets/4977187/0dca33d4-21f3-44ef-b139-78b54445d001)

**Comment by Entoarox** [comment] 2024-01-23 15:46
I am trying to get the heap uploaded so I can send it to you and hopefully make things easier for you to debug, but it is going incredibly slow unfortunately, so it will likely take at least an hour or two before this finishes.

**Comment by Technici4n** [comment] 2024-01-23 15:56
Ah, worst case you can also come on Discord for an interactive chat.

(You shouldn't expand the `<class>` as that is internal stuff shared by all instances of the same object.)

**Comment by Entoarox** [comment] 2024-01-23 16:05
Ah, I was not aware of that! Okay, having backtracked and expanded elsewhere, this is where the trail seems to be leading:
![image](https://github.com/Technici4n/Powah/assets/4977187/9defea7a-22f8-43b5-b150-ddf3d547aff4)
![image](https://github.com/Technici4n/Powah/assets/4977187/b12d679f-bbdc-412b-ad8f-282dd9cc0f5e)
I unfortunately cannot expand any deeper because EMA shows 25 of the nearly 2 million entries, and I have no clue how you expand beyond that (Or if it is needed to look deeper?)

**Comment by Entoarox** [comment] 2024-01-23 16:07
Okay, looks like I was wrong and the upload ended early, yaay for unexpected success!
Here is the linky to the zip file: https://gameon.playat.ch/heap_dump_powah.zip

**Comment by Technici4n** [comment] 2024-01-23 16:15
Ahah, looks like a memory leak in the AECapFix mod. Updating it to the latest version should fix the leak. :)

**Comment by Entoarox** [comment] 2024-01-23 17:14
> Ahah, looks like a memory leak in the AECapFix mod. Updating it to the latest version should fix the leak. :)

I see, will try this and report on any success/failure!

**Comment by Entoarox** [comment] 2024-01-23 17:32
I am already happy to report that this has fixed the issue, put the thermo's back in, and not a single peep from spark when it comes to the symptoms I previously observed about the memory leakage!

Thanks a lot for all your work Technici4n, I wish I'd known it was such a easy fix before I needed to bother you about it.

**Comment by Technici4n** [comment] 2024-01-24 07:06
Ah that's great. Well I'm happy this is resolved. :)

**Closed as completed by Technici4n** 2024-01-24 07:06 UTC
